apiVersion: v1
kind: Service
metadata:
  name: norris-fact-lb
  namespace: web
spec:
  selector:
    app: norris-fact
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  clusterIP: 
  loadBalancerIP: 
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 